name: lawnmower_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  based_battery_indicator: ^1.0.3
  based_dock_scaffold: ^1.0.3
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.24.0
  firebase_repository:
    path: packages/firebase_repository
  poly_repository:
    path: packages/poly_repository
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_blue_plus: ^1.31.13
  flutter_bluetooth_serial: ^0.4.0
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0
  location: ^5.0.3
  maps_toolkit: ^3.0.0
  syncfusion_flutter_sliders: ^24.1.47
  vector_math: ^2.1.4
  weather_repository:
    git:
      url: https://github.com/jurej1/weather_repository.git
      ref: master

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
