name: poly_repository
description: Dart package which manages the polygon domain.
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_functions: ^4.6.5
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
