name: firebase_repository
description: Dart package which manages the firebase domain.
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  http: ^0.13.5
