// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyuuUL-cmxDs_zpFBvNzFowgR1TzbYEw4',
    appId: '1:1016714013047:web:43e62579d862ee7725d972',
    messagingSenderId: '1016714013047',
    projectId: 'lawnmower-825c3',
    authDomain: 'lawnmower-825c3.firebaseapp.com',
    databaseURL: 'https://lawnmower-825c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lawnmower-825c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKdZWsTxEZoG0b1AKIRioKvYFfByemhe8',
    appId: '1:1016714013047:android:5918fa431824d8c025d972',
    messagingSenderId: '1016714013047',
    projectId: 'lawnmower-825c3',
    databaseURL: 'https://lawnmower-825c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lawnmower-825c3.appspot.com',
  );
}
